codecov:
  require_ci_to_pass: true
  disable_default_path_fixes: false

coverage:
  precision: 2
  round: down
  Type: start...end
  range: 65...70

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,files,footer"
  behavior: default
  require_changes: false
