language: java

sudo: false

services:
  - mysql

script:
  - mvn test -B
  - mvn clean verify

env:
  global:
    - CODECOV_TOKEN=:02c06ba3-5bf3-4cd0-9a70-2459dc7c4e3d

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email: false
