language: java

sudo: false

jdk:
  - oraclejdk11

services:
  - mysql

script:
  - mvn clean verify

env:
  global:
    - CODECOV_TOKEN="02c06ba3-5bf3-4cd0-9a70-2459dc7c4e3d"

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email: false
