language: java

sudo: false

script: mvn clean verify

after_success:
  - bash <(curl -s https://codecov.io/bash)

env:
  global:
    - CODECOV_TOKEN=:02c06ba3-5bf3-4cd0-9a70-2459dc7c4e3d


notifications:
  email: false
