spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/driver?serverTimezone=UTC&createDatabaseIfNotExist=true
    username: root
    password: coderslab
    initialization-mode: always # needed for using data reading from files
    data: classpath:META-INF/sql/data.sql # path to file with base SQL loading code
    continue-on-error: true # needed to avoid errors while data grom file is read

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    open-in-view: true # Open Session in View

  servlet:
    multipart: # MULTIPART (MultipartProperties)
      enabled: true  # Enable multipart uploads
      file-size-threshold: 2KB  # Threshold after which files are written to disk.
      max-file-size: 124MB  # Max file size.
      max-request-size: 512MB  # Max Request Size

  mail:
    protocol: smtp
    host: smtp.gmail.com
    port: 587
    username: sabeo.pl@gmail.com
    password: Qwer1234!#
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

logging:
  level:
    web: INFO

    org:
      hibernate:
        SQL: INFO

# Uncomment bottom line if Spring Boot debug is needed
# debug: true