spring:
  datasource:
    url: jdbc:mysql://localhost:3306/driver?serverTimezone=UTC
    username: root
    password: coderslab
    initialization-mode: always # needed for using data reading from files
    data: classpath:META-INF/sql/data.sql  # data files path, can be used for reading from multiple files

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect

  servlet:
    multipart: # MULTIPART (MultipartProperties)
      enabled: true  # Enable multipart uploads
      file-size-threshold: 2KB  # Threshold after which files are written to disk.
      max-file-size: 2MB  # Max file size.
      max-request-size: 215MB  # Max Request Size

  mail:
    protocol: smtp
    host: smtp.gmail.com
    port: 587
    username: sabeo.pl@gmail.com
    password: Qwer1234!#
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

logging:
  level:
    web: INFO

    org:
      hibernate:
        SQL: INFO

# Uncomment bottom line if Spring Boot debug is needed
# debug: true